import { StyleSheet } from 'react-native'

export const CommonStyles = StyleSheet.create({
  centering: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  flexible: { flex: 1 },
  horizontal: { flexDirection: 'row' },
  vertial: { flexDirection: 'column' },
  horizontalReverse: { flexDirection: 'row-reverse' },
  verticalReverse: { flexDirection: 'column-reverse' },
  shadowLow: {
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { height: 1.5, width: 0 },
    shadowRadius: 2,
  },
  shadowMedium: {
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { height: 4, width: 0 },
    shadowRadius: 6,
  },
  shadowHight: {
    elevation: 16,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowOffset: { height: 8, width: 0 },
    shadowRadius: 12,
  },
  marginLeftDouble: { marginLeft: 32 },
  marginTopDouble: { marginTop: 32 },
  marginRightDouble: { marginRight: 32 },
  marginBottomDouble: { marginBottom: 32 },
  marginHorizontalDouble: { marginHorizontal: 32 },
  marginVerticalDouble: { marginVertical: 32 },
  marginDouble: { margin: 32 },
  marginLeft: { marginLeft: 16 },
  marginTop: { marginTop: 16 },
  marginRight: { marginRight: 16 },
  marginBottom: { marginBottom: 16 },
  marginHorizontal: { marginHorizontal: 16 },
  marginVertical: { marginVertical: 16 },
  margin: { margin: 16 },
  marginLeftHalf: { marginLeft: 8 },
  marginTopHalf: { marginTop: 8 },
  marginRightHalf: { marginRight: 8 },
  marginBottomHalf: { marginBottom: 8 },
  marginHalf: { margin: 8 },
  marginHorizontalHalf: { marginHorizontal: 8 },
  marginVerticalHalf: { marginVertical: 8 },
  paddingLeftDouble: { paddingLeft: 32 },
  paddingTopDouble: { paddingTop: 32 },
  paddingRightDouble: { paddingRight: 32 },
  paddingBottomDouble: { paddingBottom: 32 },
  paddingDouble: { padding: 32 },
  paddingHorizontalDouble: { paddingHorizontal: 32 },
  paddingVerticalDouble: { paddingVertical: 32 },
  paddingLeft: { paddingLeft: 16 },
  paddingTop: { paddingTop: 16 },
  paddingRight: { paddingRight: 16 },
  paddingBottom: { paddingBottom: 16 },
  padding: { padding: 16 },
  paddingHorizontal: { paddingHorizontal: 16 },
  paddingVertical: { paddingVertical: 16 },
  paddingLeftHalf: { paddingLeft: 8 },
  paddingTopHalf: { paddingTop: 8 },
  paddingRightHalf: { paddingRight: 8 },
  paddingBottomHalf: { paddingBottom: 8 },
  paddingHalf: { padding: 8 },
  paddingHorizontalHalf: { paddingHorizontal: 8 },
  paddingVerticalHalf: { paddingVertical: 8 },
  textLink: {
    textDecorationStyle: 'solid',
    textDecorationLine: 'underline',
    textDecorationColor: 'black',
  },
  fontMini: {
    fontSize: 11,
    lineHeight: 18,
  },
  fontSmall: {
    fontSize: 12,
    lineHeight: 20,
  },
  fontMedium: {
    fontSize: 15,
    lineHeight: 24,
  },
  fontLarge: {
    fontSize: 18,
    lineHeight: 25,
  },
  fontXLarge: {
    fontSize: 22,
    lineHeight: 32,
  },
  fontBold: {
    fontWeight: 'bold',
  },
  widthMax: {
    width: '100%',
  },
  widthHalf: {
    width: '50%',
  },
})
